# Test Modeller for SPY Option Calls
> **Note:**
> To use OpenAI's embeddings.
> 
> Create a `.env` file and add the following line:
> ```txt
> OPENAI_API_KEY=sk-proj-fRz2xQLH4QC0KqCcPnsQT3BlbkFJHf0uNkLjXdTf4t7geTzg
> ```

In [45]:

# %pip install openai

In [46]:
# Load in data
import pandas as pd
import base64

DATA_PATH='data/output.csv'

data = pd.read_csv(DATA_PATH).dropna()
data

date                                               text  \
2   2024/05/22 12:06:00  Cosmetic Procedures\r\n\r\nPublished May 22, 2...   
3   2024/05/21 14:42:00  All Things Summer\r\n\r\nPublished May 21, 202...   
4   2024/05/20 13:02:00  Graduation 🎓\r\n\r\nPublished May 20, 2024\r\n...   
5   2024/05/17 14:26:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
6   2024/05/16 12:44:00  Beauty Report: April 2024\r\n\r\nPublished May...   
7   2024/05/15 13:28:00  Wealth Gap\r\n\r\nPublished May 15, 2024\r\n\r...   
8   2024/05/14 13:11:00  WNBA Tip-Off 🏀\r\n\r\nPublished May 14, 2024\r...   
9   2024/05/13 13:20:00  Vinyl\r\n\r\nPublished May 13, 2024\r\n\r\n\r\...   
10  2024/05/10 13:01:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
11  2024/05/09 12:44:00  Red Flags 🚩\r\n\r\nPublished May 9, 2024\r\n\r...   
12  2024/05/08 15:26:00  Mother's Day Special\r\n\r\nPublished May 8, 2...   
13  2024/05/07 14:14:00  Breakups and Relationship Standards\r\n\r\nPub...   
14  2024/05/06 12:57:00  ICYMI: April\r\n\r\nPublished May 6, 2024\r\n\...   
15  2024/05/03 13:00:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
16  2024/05/02 12:50:00  Campus Protests\r\n\r\nPublished May 2, 2024\r...   
17  2024/05/01 13:00:00  Honoring Asian and Pasifika Ancestry Month‬‬\r...   
18  2024/04/30 12:23:00  Summer Travel\r\n\r\nPublished April 30, 2024\...   
19  2024/04/29 12:53:00  Puzzles & Games\r\n\r\nPublished April 29, 202...   
20  2024/04/26 12:39:00  College Admissions and Decisions\r\n\r\nPublis...   
21  2024/04/25 13:15:00  NFL Draft 🏈\r\n\r\nPublished April 25, 2024\r\...   
22  2024/04/24 12:30:00  TV Special\r\n\r\nPublished April 24, 2024\r\n...   
23  2024/04/23 12:51:00  Gardening🌷\r\n\r\nPublished April 23, 2024\r\n...   
24  2024/04/22 12:46:00  Earth Day Special\r\n\r\nPublished April 22, 2...   
25  2024/04/19 11:59:00  Prom\r\n\r\n\r\nPublished April 19, 2024\r\n\r...   
26  2024/04/18 13:05:00  Chess and Board Games\r\n\r\nPublished April 1...   
27  2024/04/17 13:21:00  March Beauty Report\r\n\r\nPublished April 17,...   
28  2024/04/16 12:51:00  WNBA Draft 🏀\r\n\r\nPublished April 16, 2024\r...   
29  2024/04/15 15:39:00  Allergy Season\r\n\r\nPublished April 15, 2024...   
30  2024/04/12 12:28:00  Mercury Retrograde • Astrology\r\n\r\nPublishe...   
31  2024/04/11 13:00:00  Taxes • Finances\r\n\r\nPublished April 11, 20...   
32  2024/04/10 13:02:00  Coachella\r\n\r\nPublished April 10, 2024\r\n\...   
33  2024/04/09 13:25:00  4B Movement\r\n\r\nPublished April 9, 2024\r\n...   
34  2024/04/05 13:02:00  Taiwan Earthquake\r\n\r\nPublished April 5, 20...   
35  2024/04/04 13:59:00  Political Issues in Florida\r\n\r\nPublished A...   
36  2024/04/03 13:24:00  ICYMI: March\r\n\r\nPublished March 3, 2024\r\...   
37  2024/04/02 13:44:00  Cowboy Carter Special\r\n\r\nPublished April 2...   
38  2024/04/01 13:03:00  April Fools' Special\r\n\r\nPublished April 1,...   
39  2024/03/28 13:37:00  MLB Opening Day ⚾️\r\n\r\nPublished March 28, ...   
40  2024/03/27 12:39:00  Fashion Month Round-Up\r\n\r\nPublished March ...   
41  2024/03/26 12:16:00  Plant-Based Food & Drink\r\n\r\nPublished Marc...   
42  2024/03/25 13:02:00  Holi\r\n\r\nPublished March 25, 2024\r\n\r\n\r...   
43  2024/03/22 12:12:00  X-Men\r\n\r\nPublished March 22, 2024\r\n\r\n\...   
44  2024/03/21 12:57:00  Indian Premier League 🏏\r\n\r\nPublished March...   
45  2024/03/20 13:17:00  Haiti\r\n\r\nPublished March 20, 2024\r\n\r\n\...   
46  2024/03/19 13:06:00  💍Marriage and Divorce Trends💔\r\n\r\nPublished...   
47  2024/03/18 12:57:00  March Madness 🏀\r\n\r\nPublished March 18, 202...   
48  2024/03/15 12:33:00  Super Commuting\r\n\r\nPublished March 15, 202...   
49  2024/03/14 13:20:00  National Women's Soccer League ⚽\r\n\r\nPublis...   
50  2024/03/13 13:23:00  Personality Tests\r\n\r\nPublished March 13, 2...   
51  2024/03/12 13:02:00  Ramadan Mubarak\r\n\r\nPublished March 12, 202...   
52  2024/03/08 12:07:00  International Wo

In [47]:
# Left for reference for using OpenAI's embedding API
# from openai import OpenAI
# client = OpenAI()

# def get_embeddings(text):
#   response = client.embeddings.create(
#       input=text,
#       model="text-embedding-3-small"
#   )
#   return response.data[0].embedding

# data['embeddings'] = data['text'].apply(lambda x: get_embeddings(x))
# data

In [48]:
import numpy as np
from ast import literal_eval
# embeddings saved as a string into db - convert back to np array
data.embeddings = data.embeddings.apply(lambda x: np.array(literal_eval(x)))

In [49]:
# Create a new column that contains the combined values from the last 4 columns
DATA_1D_LABEL = 'one_day_labels'
DATA_2D_LABEL = 'two_day_labels'
data[DATA_1D_LABEL] = data[["one_day_call", "one_day_put"]].apply(lambda row: np.array(row), axis=1)
data[DATA_2D_LABEL] = data[["two_day_call", "two_day_put"]].apply(lambda row: np.array(row), axis=1)
data

date                                               text  \
2   2024/05/22 12:06:00  Cosmetic Procedures\r\n\r\nPublished May 22, 2...   
3   2024/05/21 14:42:00  All Things Summer\r\n\r\nPublished May 21, 202...   
4   2024/05/20 13:02:00  Graduation 🎓\r\n\r\nPublished May 20, 2024\r\n...   
5   2024/05/17 14:26:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
6   2024/05/16 12:44:00  Beauty Report: April 2024\r\n\r\nPublished May...   
7   2024/05/15 13:28:00  Wealth Gap\r\n\r\nPublished May 15, 2024\r\n\r...   
8   2024/05/14 13:11:00  WNBA Tip-Off 🏀\r\n\r\nPublished May 14, 2024\r...   
9   2024/05/13 13:20:00  Vinyl\r\n\r\nPublished May 13, 2024\r\n\r\n\r\...   
10  2024/05/10 13:01:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
11  2024/05/09 12:44:00  Red Flags 🚩\r\n\r\nPublished May 9, 2024\r\n\r...   
12  2024/05/08 15:26:00  Mother's Day Special\r\n\r\nPublished May 8, 2...   
13  2024/05/07 14:14:00  Breakups and Relationship Standards\r\n\r\nPub...   
14  2024/05/06 12:57:00  ICYMI: April\r\n\r\nPublished May 6, 2024\r\n\...   
15  2024/05/03 13:00:00  Trends Takeaways this Week\r\n\r\nPublished Ma...   
16  2024/05/02 12:50:00  Campus Protests\r\n\r\nPublished May 2, 2024\r...   
17  2024/05/01 13:00:00  Honoring Asian and Pasifika Ancestry Month‬‬\r...   
18  2024/04/30 12:23:00  Summer Travel\r\n\r\nPublished April 30, 2024\...   
19  2024/04/29 12:53:00  Puzzles & Games\r\n\r\nPublished April 29, 202...   
20  2024/04/26 12:39:00  College Admissions and Decisions\r\n\r\nPublis...   
21  2024/04/25 13:15:00  NFL Draft 🏈\r\n\r\nPublished April 25, 2024\r\...   
22  2024/04/24 12:30:00  TV Special\r\n\r\nPublished April 24, 2024\r\n...   
23  2024/04/23 12:51:00  Gardening🌷\r\n\r\nPublished April 23, 2024\r\n...   
24  2024/04/22 12:46:00  Earth Day Special\r\n\r\nPublished April 22, 2...   
25  2024/04/19 11:59:00  Prom\r\n\r\n\r\nPublished April 19, 2024\r\n\r...   
26  2024/04/18 13:05:00  Chess and Board Games\r\n\r\nPublished April 1...   
27  2024/04/17 13:21:00  March Beauty Report\r\n\r\nPublished April 17,...   
28  2024/04/16 12:51:00  WNBA Draft 🏀\r\n\r\nPublished April 16, 2024\r...   
29  2024/04/15 15:39:00  Allergy Season\r\n\r\nPublished April 15, 2024...   
30  2024/04/12 12:28:00  Mercury Retrograde • Astrology\r\n\r\nPublishe...   
31  2024/04/11 13:00:00  Taxes • Finances\r\n\r\nPublished April 11, 20...   
32  2024/04/10 13:02:00  Coachella\r\n\r\nPublished April 10, 2024\r\n\...   
33  2024/04/09 13:25:00  4B Movement\r\n\r\nPublished April 9, 2024\r\n...   
34  2024/04/05 13:02:00  Taiwan Earthquake\r\n\r\nPublished April 5, 20...   
35  2024/04/04 13:59:00  Political Issues in Florida\r\n\r\nPublished A...   
36  2024/04/03 13:24:00  ICYMI: March\r\n\r\nPublished March 3, 2024\r\...   
37  2024/04/02 13:44:00  Cowboy Carter Special\r\n\r\nPublished April 2...   
38  2024/04/01 13:03:00  April Fools' Special\r\n\r\nPublished April 1,...   
39  2024/03/28 13:37:00  MLB Opening Day ⚾️\r\n\r\nPublished March 28, ...   
40  2024/03/27 12:39:00  Fashion Month Round-Up\r\n\r\nPublished March ...   
41  2024/03/26 12:16:00  Plant-Based Food & Drink\r\n\r\nPublished Marc...   
42  2024/03/25 13:02:00  Holi\r\n\r\nPublished March 25, 2024\r\n\r\n\r...   
43  2024/03/22 12:12:00  X-Men\r\n\r\nPublished March 22, 2024\r\n\r\n\...   
44  2024/03/21 12:57:00  Indian Premier League 🏏\r\n\r\nPublished March...   
45  2024/03/20 13:17:00  Haiti\r\n\r\nPublished March 20, 2024\r\n\r\n\...   
46  2024/03/19 13:06:00  💍Marriage and Divorce Trends💔\r\n\r\nPublished...   
47  2024/03/18 12:57:00  March Madness 🏀\r\n\r\nPublished March 18, 202...   
48  2024/03/15 12:33:00  Super Commuting\r\n\r\nPublished March 15, 202...   
49  2024/03/14 13:20:00  National Women's Soccer League ⚽\r\n\r\nPublis...   
50  2024/03/13 13:23:00  Personality Tests\r\n\r\nPublished March 13, 2...   
51  2024/03/12 13:02:00  Ramadan Mubarak\r\n\r\nPublished March 12, 202...   
52  2024/03/08 12:07:00  International Wo

In [50]:
TRAIN_TEST_RATIO = 0.2

def split_dataset(X, y1, y2, test_ratio):
    shuffled_indices = np.random.permutation(len(X))
    test_set_size = int(len(X) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return list(X.iloc[train_indices].values), y1.iloc[train_indices].to_numpy(), y2.iloc[train_indices].to_numpy(), list(X.iloc[test_indices].values), y1.iloc[test_indices].to_numpy(), y2.iloc[test_indices].to_numpy()
X_train, t1_train, t2_train, X_test, t1_test, t2_test = split_dataset(data.embeddings, data[DATA_1D_LABEL], data[DATA_2D_LABEL],  TRAIN_TEST_RATIO)

#print(f"X_train.shape:\t{X_train.shape}")
print(f"t1_train.shape:\t{t1_train.shape}")
#print(f"X_test.shape:\t{X_test.shape}")
print(f"t1_test.shape:\t{t1_test.shape}")

t1_train.shape:	(48,)
t1_test.shape:	(11,)


In [51]:
t1_train_reshaped = np.vstack(t1_train)
t1_train_reshaped.shape
t1_test_reshaped = np.vstack(t1_test)
t1_test_reshaped.shape

(11, 2)

In [52]:
t2_train_reshaped = np.vstack(t2_train)
t2_train_reshaped.shape
t2_test_reshaped = np.vstack(t2_test)
t2_test_reshaped.shape

(11, 2)

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.multioutput import MultiOutputRegressor, RegressorChain
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
from sklearn.svm import LinearSVR, SVR

# Feature Extraction
pipe = Pipeline([
  ('reg', MultiOutputRegressor(estimator=HistGradientBoostingRegressor()))
])

Creating a scorer for calculating the aggreated MSE of the 2d label.

In [54]:
from sklearn.metrics import make_scorer

def mse(y_true, y_pred):
  diff = np.square(y_true - y_pred)
  return np.mean(diff, axis=0)

def mse_scorer(y_true, y_pred):
  diff = np.square(y_true - y_pred)
  return np.mean(diff)

score = make_scorer(mse_scorer, greater_is_better=False)

In [55]:
from sklearn.model_selection import GridSearchCV
ESTIMATORS = [
  RandomForestRegressor() # previously tested a bunch of hyper paramters (and models) in the end random forest default was fine
  ]
param_grid = [
    {
        "reg__estimator": ESTIMATORS
    }
]
grid1 = GridSearchCV(pipe, param_grid=param_grid, scoring=score)
grid1.fit(X_train, t1_train_reshaped)

grid2 = GridSearchCV(pipe, param_grid=param_grid, scoring=score)
grid2.fit(X_train, t2_train_reshaped)

GridSearchCV(estimator=Pipeline(steps=[('reg',
                                        MultiOutputRegressor(estimator=HistGradientBoostingRegressor()))]),
             param_grid=[{'reg__estimator': [RandomForestRegressor()]}],
             scoring=make_scorer(mse_scorer, greater_is_better=False, response_method='predict'))

In [56]:
model1 = grid1.best_estimator_
model2 = grid2.best_estimator_

print(f"Test Mean Squared Error:\t{mse(t1_test_reshaped, model1.predict(X_test))}")
print(f"Test Score:\t{score(model1, X_test, t1_test_reshaped)}")
print(f"Train Mean Squared Error:\t{mse(t1_train_reshaped, model1.predict(X_train))}")
print(f"Train Score:\t{score(model1, X_train, t1_train_reshaped)}")

Test Mean Squared Error:	[ 7.47018694 14.43534181]
Test Score:	-10.952764377272727
Train Mean Squared Error:	[1.29095383 1.85820129]
Train Score:	-1.5745775626041663


In [58]:
# Predict

"""
Commenting out code used to creating the embeddings
"""
# filepath1 = "data/1d-may-24-outlook.txt"
# filepath2 = "data/2d-may-23-outlook.txt" 

# with open(filepath1, 'r') as file:
#     predict_data1 = base64.b64decode(file.read()).decode()
# with open(filepath2, 'r') as file:
#     predict_data2 = base64.b64decode(file.read()).decode()
# predict_data1 = get_embeddings(predict_data1)
# predict_data2 = get_embeddings(predict_data2)
# np.save('data/1d-may-24-outlook.embeddings.npy', np.array(predict_data1).reshape(1,-1))
# np.save('data/2d-may-23-outlook.embeddings.npy', np.array(predict_data2).reshape(1,-1))

predict_data1 = np.load('data/1d-may-24-outlook.embeddings.npy')
predict_data2 = np.load('data/2d-may-23-outlook.embeddings.npy')


In [59]:
# Actual For May 24 T+1 predicted (high, low)
# (1.02999999999997, -2.37)
model1.predict(np.array(predict_data1).reshape(1,-1))

array([[ 3.2653, -0.6839]])

In [60]:
# Actual For May 24 T+2 predicted (high, low)
# (TBD, TBD)
model2.predict(np.array(predict_data1).reshape(1,-1))

array([[3.2683, 0.0708]])

In [61]:
# Actual For May 23 T+1 predicted (high, low)
# (0.919999999999959, -2.46900000000005)
model1.predict(np.array(predict_data2).reshape(1,-1))

array([[ 2.6832, -2.2841]])

In [62]:
# Actual For May 23 T+2 predicted (high, low)
# (1.15999999999997, -2.24000000000001)
model2.predict(np.array(predict_data2).reshape(1,-1))

array([[ 2.5368, -2.817 ]])